// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlYel7AY_iGJq-TYDsaUWKclIA5XeEK5U',
    appId: '1:302717697075:web:83ad084345934e0e44b746',
    messagingSenderId: '302717697075',
    projectId: 'swim-force-plus',
    authDomain: 'swim-force-plus.firebaseapp.com',
    storageBucket: 'swim-force-plus.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHLtwj85JDS0mW_CFHSdaXZglRHQzEGVQ',
    appId: '1:302717697075:android:ad5e9fc6430df10044b746',
    messagingSenderId: '302717697075',
    projectId: 'swim-force-plus',
    storageBucket: 'swim-force-plus.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBf7MgoYv5DH0Neet7Uqqui5lp6k5nJb3k',
    appId: '1:302717697075:ios:8f3813817badecfc44b746',
    messagingSenderId: '302717697075',
    projectId: 'swim-force-plus',
    storageBucket: 'swim-force-plus.firebasestorage.app',
    iosBundleId: 'com.example.startForce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBf7MgoYv5DH0Neet7Uqqui5lp6k5nJb3k',
    appId: '1:302717697075:ios:8f3813817badecfc44b746',
    messagingSenderId: '302717697075',
    projectId: 'swim-force-plus',
    storageBucket: 'swim-force-plus.firebasestorage.app',
    iosBundleId: 'com.example.startForce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlYel7AY_iGJq-TYDsaUWKclIA5XeEK5U',
    appId: '1:302717697075:web:250d0cd5b797fde744b746',
    messagingSenderId: '302717697075',
    projectId: 'swim-force-plus',
    authDomain: 'swim-force-plus.firebaseapp.com',
    storageBucket: 'swim-force-plus.firebasestorage.app',
  );
}
