// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIXKJjNOl6NHzxpYKT4MhTdhkFPdHmYUE',
    appId: '1:315211558842:web:3471bcf3a369cf14163783',
    messagingSenderId: '315211558842',
    projectId: 'mavaquatics2026',
    authDomain: 'mavaquatics2026.firebaseapp.com',
    storageBucket: 'mavaquatics2026.firebasestorage.app',
    measurementId: 'G-XRWCK80BMS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACbrSajQF1ATloT7wOPCnOjiAOW7NzlR8',
    appId: '1:315211558842:android:ce2dcc856eb2611a163783',
    messagingSenderId: '315211558842',
    projectId: 'mavaquatics2026',
    storageBucket: 'mavaquatics2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVlVKrdDmV0ZYcX_s7y1UFw5gTsQyGhkg',
    appId: '1:315211558842:ios:9a9351d953a80222163783',
    messagingSenderId: '315211558842',
    projectId: 'mavaquatics2026',
    storageBucket: 'mavaquatics2026.firebasestorage.app',
    iosBundleId: 'com.example.mavaquatics2026',
  );
}
